In [2]:
import numpy as np

In [3]:
#we use genfromtxt instead of importing pandas and using pd.read
df=np.genfromtxt('normal_distribution.csv',delimiter=',')

In [4]:
df[0:2]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

In [5]:
#mean
np.mean(df)

100.16536917390624

In [6]:
#mean for the second row
np.mean(df[1])

97.27899259

In [7]:
#mean for the first column
np.mean(df[:,0])

99.76743510416668

In [9]:
#mean for the fourth column
np.mean(df[:,3])

101.84493159749998

In [10]:
#median
np.median(df)

100.18206203

In [11]:
#median for the last row
np.median(df[-1])

99.18748092

In [13]:
#variance
np.var(df)

23.408155574137027

In [24]:
#axis =0  is used to get variance per column , axis=1 it would mean row
np.var(df,axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [25]:
#axis=1 is used to get variance per column 
np.var(df,axis=1)

array([11.47831221, 19.87124806, 38.76626578, 51.82791356, 24.08117728,
       22.86112657, 22.39746721, 16.95556067, 14.99854574, 28.70862927,
       10.31592621, 15.62432312, 51.65273836, 21.93340236, 17.11660913,
       22.57008154, 11.02824211,  5.01674729, 17.35648886, 11.40121072,
       10.98051411, 19.32123956, 12.93285875, 16.47774976])

In [26]:
#standard deviation
np.std(df)

4.838197554269257

In [27]:
#std value of values from the first 2 rows and columns
np.std(df[:2,:2])

4.308326898129258

In [31]:
#std for first three rows and first two columns  df[row_start:row_end,column_start:column_end]
np.std(df[:3,:2])

3.7371052088490777

In [32]:
 #indexing in numpy

In [33]:
#index a single element in outermost dimension
df[0]

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

In [34]:
#index in reversed order in outermost dimension
df[-1]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [36]:
#index single element in the two dimensional data
df[1,1]

97.10439252

In [37]:
#index in reversed order in the two dimensional data
df[-1,-1]

100.07721494

In [39]:
#slicing

In [40]:
#row 1 and 2
df[1:3]

array([[ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286]])

In [41]:
df[7:11]

array([[ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.74767493,  97.57544275,  92.5748759 ],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318,
        101.29326772, 100.85447132, 101.2226037 , 106.03868807],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524,
         92.75048583, 101.72074646,  96.96851209, 103.29147111],
       [101.3514185 , 100.37372248, 106.6471081 , 100.61742813,
        105.0320535 ,  99.35999981,  98.87007532,  95.85284217]])

In [42]:
#last row with elements reversed
df[-1,::-1]

array([100.07721494, 106.05042487,  98.75108352,  93.97853495,
        97.62787811, 104.51786419,  99.62387832,  94.11176915])

In [44]:
#last 4 rows every other element upto index 6
df[-5:-1,:6:2]

array([[ 96.76814836, 101.79132774,  98.29243952],
       [106.89005002, 102.26648279,  99.94318168],
       [ 99.80873105, 106.46476468, 100.69156231],
       [ 96.10020311, 100.80409326,  98.61325194]])

In [45]:
# 2x2 subset of data
df[:2,:2]

array([[ 99.14931546, 104.03852715],
       [ 92.02628776,  97.10439252]])

In [50]:
#first 5 rows and 6 columns
df[:5,:6]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 ],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357]])

In [52]:
#from row 1 to 3 columns 1 to 3
df[1:4,1:4]

array([[ 97.10439252,  99.32066924,  97.24584816],
       [ 95.17750125,  90.93318132, 110.18889465],
       [100.96781394, 100.40118279, 113.42090475]])

In [46]:
#splitting

In [ ]:
#split vertica